# -*- coding: utf-8 -*-
"""SML_WebApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nNnt8EdB2ohwKsx6R98e3eUV1Zrl2Vhu
"""

# ! pip install streamlit

import streamlit as st

st.title('Bank Transactions Fraud Detection')
col1, col2, col3 = st.columns((1, 8, 1))
with col2:
    st.text('A ML application to seamlessly detect fradulent bank transactions')

tab1, tab2, tab3, tab4, tab5 = st.tabs(["🔎 Overview", "📃 Dataset", "📅 Exploratory Data Analysis", "📈 Model Performance", "✏️ References"])


with tab1: 
    # overview
    st.markdown("<h5 style='text-align: center; color: #DA0C81;'>Why this topic?</h5>", unsafe_allow_html=True)

    st.write("The banking sector’s shift from traditional physical locations to digital channels\
    has offered customers unprecedented convenience, but it has also increased the risk of fraud\
    for customers and institutions alike. In this study, we discuss the pressing need for robust\
    fraud detection & prevention systems in the context of evolving technological environments.\
    We introduce a graph-based machine learning model that is specifically designed to detect\
    fraudulent activity in various types of banking operations, such as credit card transactions,\
    debit card transactions, and online banking transactions. This model uses advanced methods for\
    anomalies, behaviors, and patterns to analyze past transactions and user behavior almost immediately.\
    We provide an in-depth methodology for evaluating fraud detection systems based on parameters\
    such as: Accuracy Recall rate False positive rate ROC curves. The paper is structured in such\
    a way that the reader is guided through the importance of fraud prevention, the body of previous\
    research, data sources, methodology, and concrete results. The findings can be used by financial\
    institutions to develop and enhance fraud detection strategies as they demonstrate the effectiveness\
    and reliability of the proposed approach. This study emphasizes the critical role that innovative\
    technologies play in safeguarding the financial sector from the ever-changing strategies of\
    fraudsters while also enhancing banking security.")

    st.image("SML Project Method.png", width=700)

with tab2:
    # dataset
    st.markdown("<h5 style='text-align: center; color: #DA0C81;'>The Data</h5>", unsafe_allow_html=True)

    st.write("We have utilised a publicly available dataset known as [The Banksim dataset]\
    (https://www.kaggle.com/datasets/ealaxi/banksim1) for development of this project.")

    st.markdown("<h5 style='text-align: center; color: #DA0C81;'>Features</h5>", unsafe_allow_html=True)
    st.write("no NAs")
    st.write("Step: represents the day when the transaction happened. There is a total of 180 steps, \
    so the data runs for six months. This variable was removed from the dataset.")
    
    st.write("Customer: represents the unique ID of the person who initialized the transaction. \
    It is formed by the letter C, followed by a unique sequence of 10 numbers. \
    There is a total of 4,109 unique customers available in the dataset.")
    
    st.write("Age: this variable is split in age intervals, starting from 0 to 6 and the\
    letter U which stands for Unknown. Age is Unknown only for transactions\
    that have the gender equal to Enterprise. The coding for the numbers is:")
    st.write("0: less than 18 years old")
    st.write("1: between 19 and 25 years old")
    st.write("2: between 26 and 35 years old")
    st.write("3: between 36 and 45 years old")
    st.write("4: between 46 and 55 years old")
    st.write("5: between 56 and 65 years old")
    st.write("6: older than 65 years old")
    
    st.write("Gender: this variable is coded as F for Female, M for Male, E for Enterprise\
    and U for Unknown. The Unknown group has around 170 customers aged in groups 1, 2 and 3.")
    
    st.write("Merchant: this variable represents the unique ID of the party which receives the transaction.\
    Similar to customer ID, the sequence is formed by the letter M, followed by a series of 9 numbers.\
    There is a total of 50 unique merchants in the dataset.")

    st.write("Category: there are 15 unique categories that label the general type of the transaction: transportation,\
    food, health, wellness and beauty, fashion, bars and restaurant, hyper, sports and toys, tech, home,\
    hotel services, other services, contents, travel, leisure.")

    st.write("Amount: represents the value of the transaction. There are only 52 values equal to 0 and no negative values.")
    st.write("Fraud: a flag column coded with 0 if the transaction was clean and with 1 if the transaction was fraudulent.")
    st.write("zipcodeOri and zipMerchant: these two features were removed from the dataset, as they contained a constant value\
    of 28007, which is a postal code in Ansonville, North Carolina, United States. Therefore, the amount will be from now on expressed in us dollars.")

with tab3:
    col1, col2, col3 = st.columns((1, 3, 1))
    with col1:
        st.write(' ')
    with col2:
       st.image("beforeSMOTE.png", width=500)
       
       st.divider()
       st.image("afterSMOTE.png", width=500)
       
    with col3:
        st.write(' ')


with tab4:
    
    col1, col2, col3 = st.columns((1, 3, 1))
    with col1:
        st.write(' ')
    with col2:
       st.subheader("Best performing model: XGBoost")

       st.text("ROC Curve:")
       st.image("xgboost_roc.png", width=500)
       
       st.divider()

       st.text("Confusion Matrix:")
       st.image("xgboost_cm.png", width=500)
       
    with col3:
        st.write(' ')

with tab5:
    st.subheader("Some of the reference papers are as below: ")

    st.write('[1] Gyamfi, Nana Kwame, and Jamal-Deen Abdulai. "Bank fraud detection using support vector machine."\
    In 2018 IEEE 9th Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON), pp. 37-41. IEEE, 2018.')

    st.write('[2] Magomedov, Shamil, Sergei Pavelyev, Irina Ivanova, Alexey Dobrotvorsky, Marina Khrestina, \
    and Timur Yusubaliev. "Anomaly detection with machine learning and graph databases in fraud management." \
    International Journal of Advanced Computer Science and Applications 9, no. 11 (2018).')

    st.write('[3] Radhika, M., Komarthi Vyshnavi Devi, Mavuri Divya, and Ganthakuri Sree Lakshmi.\
     "IDENTIFICATION OF FRAUD DETECTION FROM CREDIT CARD TRANSACTIONS USING ML." Journal of Science\
     and Technology 8, no. 04 (2023).')

    st.write("[Link to Report](https://docs.google.com/document/d/1K1kO_AeH4P7R0lOxdKea0gcOMwOqGePk/edit)")


